### PR TITLE
make bot to ignore further commands when self destruct ordered

### PR DESCRIPTION
**Pull request by ruby3141**
Sagira would be pissed when someone tell her to die.

### CODE REVIEW

**Comment by nOctaveLay** [comment]
In my console, What I show
```
Destiny-Bot\main.py", line 68, in on_message
    if message.auther.id in ignore_user_set:
AttributeError: 'Message' object has no attribute 'auther'
```

**Comment by nOctaveLay** [comment]
+ **auther** must be **author**

**Comment by ruby3141** [comment]
typo fixed.

**Comment by nOctaveLay** [comment]
First, you need to consider the length of option
if the function checking the length of option is after the function checking option[0], you can see error because of option[0]
```IndexError: list index out of range```

Second, I should be ignored after I type "사기라 자폭해". but It doesn't work

**Comment by ruby3141** [comment]
fixed

**Pull request merged**
